### ISSUE TITLE
Drugs by Concept Class histogram

### ISSUE THREAD

**Issue by PRijnbeek** [anthonysena/DrugUtilization#8]
Is it possible to make  a histogram per ingredient of the type of the concept_id, e.g., Clinical Drug,  Clinical Drug From, Branded Drug?

This is interesting to see accross the data sources.

**Comment by anthonysena** [comment]
I created a "Target Concept Type" dashboard that I think should be a good start here.

**Comment by cgreich** [comment]
BTW: We need to avoid the word "type". It's super annoying, because it often is the right term, but now it is a privileged term Type Concepts, which really are "Provenance Concepts". Unfortunately, we effed this up in V2 of the OMOP CDM way back in prehistoric times.

**Comment by anthonysena** [comment]
In reading @PRijnbeek's original idea here, I wound up using concept class ID for this work. So we can avoid the "type" term here. I've revised the dashboard to "Drugs by Concept Class" instead.

**Comment by PRijnbeek** [comment]
Yes agree we should not say type indeed but use our CDM language instead.

**Comment by anthonysena** [comment]
Updated the issue to reflect the new name. Closing this out since I've put together a draft dashboard for this item. We can re-open or start new issues for revisions. Thanks!
